#page title
# Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.
page_title: Motorcycle Theory Untangled

# App Info
# Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
# ios_app_id: 1512489096

# Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
appstore_link:

# Enter Google Play Store URL.
playstore_link:

# Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
# Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").
presskit_download_link:

# Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_icon: assets/logo.png

# Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_name: Motorcycle Theory Untangled

# Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price: £2.99
app_description: Pass first time. Updated for 2020.

# Set to true to show a smart app banner at top of page on mobile devices.
enable_smart_app_banner: true



# Information About Yourself
your_name: Dripl
your_link: https://dripl.co.uk
your_city:
email_address: hello@dripl.co.uk
facebook_username:
instagram_username:
twitter_username: alixedi
github_username: alixedi
youtube_username:


# Feature List
features:

  - title: We will tell you when you are ready
    description: Get cracking with the practice and mock tests and keep an eye on the progress rings on the home screen. When the rings are about to close, you are ready. Go book that test.
    fontawesome_icon_name: check-square

  - title: Simplicity is the key
    description: Its right there in the name. Untangled means an app you can fire up on your commute, while waiting for your kettle to boil or while your partner is watching Strictly (don't).
    fontawesome_icon_name: list-ol

  - title: Hazard Perception included
    description: Or maybe you can convince your partner to watch Hazard Perception clips together? They are included in the app. No extra charges.
    fontawesome_icon_name: play

  - title: Doesn't cost a fiver
    description: Talking about charges, why does every theory app costs a fiver? Well, not any more. You can have our app for the grand price of a skinny latte. Buy a celebrity bobblehead separately if you are into that. Or not?
    fontawesome_icon_name: pound-sign

  - title: Licensed materials from the DVSA
    description: The learning materials for our app are licensed from the DVSA. 700-odd questions, 10 scenarios & 34 hazard perception clips. From the people who make the real test.
    fontawesome_icon_name: certificate

  - title: Case-studies included
    description: We have included 10 case studies with about 20 questions each. This should cover the part in the test that other apps often miss out.
    fontawesome_icon_name: theater-masks

  - title: A sprinkle of Science
    description: Learning 700 questions can be daunting. So we have build the app with spaced repetition - the science that will ensure that you don't forget what you have learned. As you go through the material, questions will repeat until you get them right several times.
    fontawesome_icon_name: brain

  - title: Privacy first
    description: We don’t like snooping. We are not interested in your email, your gender or what you post on Facebook. Pass the test. Delete the app. Move on.
    fontawesome_icon_name: lock

  - title: A new feature every other week
    description: Finally, we would like this to be a collaboration. Dripl x You. We will release a new feature every other week. Tell us what you want. We will make it happen.
    fontawesome_icon_name: gift


# Theme Settings
topbar_color: "#000000"
topbar_transparency: 0.1
topbar_title_color: "#ffffff"

cover_image: assets/headerimage.jpg
cover_overlay_color: "#363b3d"
cover_overlay_transparency: 0.8

# Set to: blue, black, yellow, coral or white.
device_color: black

body_background_color: "#ffffff"

link_color: "#1d63ea"

app_title_color: "#ffffff"
app_price_color: "#ffffff"
app_description_color: "#ffffff"

feature_title_color: "#000000"
feature_text_color: "#666666"

feature_icons_foreground_color: "#1d63ea"
feature_icons_background_color: "#e6e6e6"

social_icons_foreground_color: "#666666"
social_icons_background_color: "#e6e6e6"

footer_text_color: "#666666"




####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
